apiVersion: v1
data:
  elasticsearch.yml: |
    cluster:
      name: elasticsearch-cluster
    node:
      master: ${NODE_MASTER}
      data: ${NODE_DATA}
      name: ${NODE_NAME}
      ingest: ${NODE_INGEST}
      max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}
    processors: ${PROCESSORS:1}
    network.host: ${NETWORK_HOST}
    path:
      data: /data/data
      logs: /data/log
    bootstrap:
      memory_lock: ${MEMORY_LOCK}
    http:
      enabled: ${HTTP_ENABLE}
      compression: true
      cors:
        enabled: true
        allow-origin: "*"
    discovery:
      zen:
        ping.unicast.hosts: elasticsearch-discovery
        minimum_master_nodes: ${NUMBER_OF_MASTERS}
    #xpack.license.self_generated.type: basic
    #xpack.security.enabled: false
    #xpack.monitoring.enabled: false
    #xpack.ml.enabled: false
    cluster.routing.allocation.enable: all
    cluster.routing.rebalance.enable: all
    cluster.routing.allocation.allow_rebalance: indices_all_active
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: es-configmap