apiVersion: v1
data:
  elasticsearch.yml: |
    cluster:
      name: elasticsearch-cluster
      initial_master_nodes: ${INITIAL_MASTER_NODE}
    node:
      master: ${NODE_MASTER}
      data: ${NODE_DATA}
      name: ${NODE_NAME}
      ingest: ${NODE_INGEST}
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#max-local-storage-nodes
      max_local_storage_nodes: 1
    processors: ${PROCESSORS:1}
    network.host: ${NETWORK_HOST:_eth0_}
    path:
      data: /data/data
      logs: /data/log
    bootstrap:
      # Kubernetes requires swap is turned off, so memory lock is redundant
      memory_lock: false
    http:
      compression: true
      cors:
        enabled: true
        allow-origin: "*"
    discovery:
      seed_hosts: elasticsearch-discovery
    #xpack.license.self_generated.type: basic
    #xpack.security.enabled: false
    #xpack.monitoring.enabled: false
    #xpack.ml.enabled: false
    cluster.routing.allocation.enable: all
    cluster.routing.rebalance.enable: all
    cluster.routing.allocation.allow_rebalance: indices_all_active
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: es-configmap
  namespace: logging
