apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: full
spec:
  selector:
    component: elasticsearch
    role: full
  ports:
  - name: http
    port: 9200
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 30m
spec:
  rules:
  - host: javigs82.me
    http:
      paths:
      - path: /elasticsearch
        backend:
          serviceName: elasticsearch
          servicePort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    component: elasticsearch
    role: full
spec:
  selector:
    component: elasticsearch
    role: full
  ports:
  - name: transport
    port: 9300
    protocol: TCP
