apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: es-full
  namespace: logging
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: full
